# Variables y placeholder

In [1]:
import tensorflow as tf

In [2]:
tensor =  tf.random.uniform((5,5),0,1)

In [3]:
variable = tf.Variable(initial_value = tensor)

In [4]:
print(variable)

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[0.143489  , 0.64994013, 0.964515  , 0.29525495, 0.02442634],
       [0.61332023, 0.98031735, 0.6948893 , 0.94323874, 0.59393346],
       [0.2664137 , 0.58450675, 0.81404865, 0.20892727, 0.78765535],
       [0.9201354 , 0.19562948, 0.9835894 , 0.5311992 , 0.8409245 ],
       [0.52418756, 0.09072042, 0.9686624 , 0.16565919, 0.32161963]],
      dtype=float32)>


In [6]:
resultado = variable
print(resultado)
tf.print(resultado)

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[0.143489  , 0.64994013, 0.964515  , 0.29525495, 0.02442634],
       [0.61332023, 0.98031735, 0.6948893 , 0.94323874, 0.59393346],
       [0.2664137 , 0.58450675, 0.81404865, 0.20892727, 0.78765535],
       [0.9201354 , 0.19562948, 0.9835894 , 0.5311992 , 0.8409245 ],
       [0.52418756, 0.09072042, 0.9686624 , 0.16565919, 0.32161963]],
      dtype=float32)>
[[0.143489 0.649940133 0.964515 0.295254946 0.0244263411]
 [0.613320231 0.980317354 0.694889307 0.943238735 0.593933463]
 [0.266413689 0.58450675 0.814048648 0.208927274 0.787655354]
 [0.920135379 0.195629478 0.983589411 0.531199217 0.840924501]
 [0.524187565 0.0907204151 0.968662381 0.165659189 0.32161963]]


In [7]:
# placeholder vacion y sirven para alimentar al modeloa

In [9]:
@tf.function
def my_function(x):
  y = 2 * x
  return y

In [11]:
y_val = my_function(tf.constant(1))
print(y_val)

tf.Tensor(2, shape=(), dtype=int32)


In [12]:
tf.print(y_val)

2
